server:
  port: 5000

spring:
  cloud:
    config:
      name: config
      server:
        git:
          uri: https://github.com/ilie50/mail-microservices
          search-paths: config-files*
          repos:
            local:
              pattern: mail/local*
              uri: file:///C:/Projects/others/mail-microservices
  application:
    name: config